Repository iTechLibrary/mimir, pull requests merged in 2022-08, with the labels that each got.

#308 feat add chitai-gorod service
  packages/metadata-service/src/readers/chitai-gorod.service/index.ts
  packages/metadata-service/src/readers/db.service.ts
  packages/metadata-service/src/readers/ozby.service/index.ts
  packages/metadata-service/src/readers/reader.service.ts
  packages/metadata-service/src/readers/readers.modules.ts
  packages/metadata-service/src/types/index.ts
  tsconfig.base.json
Labels: BE

#311 [303] Claim history
  packages/apiserver/src/resources/item/item.resolver.ts
  packages/apiserver/src/resources/item/item.service.ts
  packages/apiserver/src/resources/item/item.shema.graphql
  packages/apollo-client/src/graphql.schema.json
  packages/apollo-client/src/lib/generated/client-types.ts
  packages/apollo-client/src/lib/queries/getItemsForClaimHistory.gql
  packages/frontapp/src/app/components/BookCard/index.tsx
  packages/frontapp/src/app/components/BookStatus/index.tsx
  packages/frontapp/src/app/pages/HistoryOfClaimPage.tsx
  packages/global-types/src/lib/global-types.ts
  packages/localization/src/lib/resources.ts
Labels: FE, BE, GQL

#334 [fix/333]: Tab buttons should use pointer cursor
  packages/frontapp/src/app/components/ClaimTable/index.tsx
Labels: FE, BUG

#339 Bug/Fix design on manager homepage
  packages/frontapp/src/app/components/ManagerInfoCard/index.tsx
  packages/frontapp/src/app/components/NotificationList/index.tsx
  packages/frontapp/src/app/hooks/useRoutes.tsx
Labels: FE, BUG

#352 Feature/Donates from user search
  packages/apiserver/src/resources/notifications/notification.schema.graphql
  packages/apollo-client/src/lib/mutations/сreateAnswerNotification.gql
  packages/apollo-client/src/lib/queries/getAllMaterialsForDonate.gql
  packages/frontapp/src/app/app.tsx
  packages/frontapp/src/app/components/OneDonatedBookPreview/index.tsx
  packages/frontapp/src/app/pages/DonatesFromUser.tsx
Labels: FE

#357 Feature/User history of donates page
  packages/apiserver/src/resources/materials/material.resolver.ts
  packages/apiserver/src/resources/materials/material.schema.graphql
  packages/apiserver/src/resources/materials/material.service.ts
  packages/apollo-client/src/graphql.schema.json
  packages/apollo-client/src/lib/generated/client-types.ts
  packages/apollo-client/src/lib/queries/getAllDonatedMaterialsByPerson.gql
  packages/frontapp/src/app/components/BookCard/index.tsx
  packages/frontapp/src/app/components/BookCardExtended/index.tsx
  packages/frontapp/src/app/components/BookStatus/index.tsx
  packages/frontapp/src/app/globalUI/Status/index.tsx
  packages/frontapp/src/app/pages/HistoryOfClaimPage.tsx
  packages/frontapp/src/app/pages/HistoryOfDonatePage.tsx
  packages/global-types/src/lib/global-types.ts
  packages/global-types/src/lib/statusTypes.ts
  packages/localization/src/lib/resources.ts
Labels: FE, BE

#362 [345] Permissions
  packages/apiserver/src/app/app.module.ts
  packages/apiserver/src/auth/auth.guard.ts
  packages/apiserver/src/migrations/1660747651414-migrationMy.ts
  packages/apiserver/src/permission/grant.decorator.ts
  packages/apiserver/src/permission/grant.guard.ts
  packages/apiserver/src/resources/blocked-users/blocked-users.guard.ts
  packages/apiserver/src/resources/persons/person.entity.ts
  packages/apiserver/src/resources/persons/person.resolver.ts
  packages/apiserver/src/resources/persons/person.schema.graphql
  packages/apiserver/src/schema.graphql
  packages/apollo-client/src/graphql.schema.json
  packages/apollo-client/src/lib/generated/client-types.ts
  packages/apollo-client/src/lib/mutations/changePersonRole.gql
  packages/apollo-client/src/lib/queries/getOnePerson.gql
  packages/frontapp/src/app/components/UserCard/index.tsx
  packages/global-types/src/lib/global-types.ts
  packages/localization/src/lib/resources.ts
Labels: FE, BE, GQL

#363 Fix bugs #335 and #336
  packages/frontapp/src/app/components/BookCardExtended/index.tsx
  packages/frontapp/src/app/components/BookStatus/index.tsx
  packages/frontapp/src/app/components/ClaimHistory/index.tsx
  packages/frontapp/src/app/components/ManagerInfoCard/index.tsx
  packages/frontapp/src/app/components/NotificationList/index.tsx
  packages/frontapp/src/app/components/OverdueList/index.tsx
  packages/frontapp/src/app/models/helperFunctions/claimHistory.ts
  packages/frontapp/src/app/models/helperFunctions/converTime.ts
  packages/frontapp/src/app/models/helperFunctions/getCurrentStatus.ts
  packages/frontapp/src/app/pages/HomePage.tsx
  packages/localization/src/lib/resources.ts
Labels: FE

#369 Fix bug with claim table
  packages/frontapp/src/app/pages/BookPreview.tsx
  packages/localization/src/lib/resources.ts
Labels: FE, BUG
